name: wgc-embedded

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    env:
      BUILD_NUMBER: ${{ github.run_number }}

    runs-on: ubuntu-latest

    steps:
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"

      - uses: actions/checkout@v3

      - name: Mirror commits to Codeberg
        uses: spyoungtech/mirror-action@v0.7.0
        with:
          REMOTE: "https://codeberg.org/edigonzales/wgc-embedded.git"
          GIT_USERNAME: ${{ secrets.CODEBERG_USER }}
          GIT_PASSWORD: ${{ secrets.CODEBERG_PASSWORD }}
