name: wgc-embedded

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    env:
      BUILD_NUMBER: ${{ github.run_number }}

    runs-on: ubuntu-latest

    steps:
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror commits to Codeberg
        uses: spyoungtech/mirror-action@v0.7.0
        with:
          REMOTE: "https://codeberg.org/edigonzales/wgc-embedded.git"
          GIT_USERNAME: ${{ secrets.CODEBERG_USER }}
          GIT_PASSWORD: ${{ secrets.CODEBERG_PASSWORD }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Test and build Jar
        run: |
          ./mvnw clean test -DexcludedGroups="docker"
          ./mvnw -Penv-prod,native clean package -DexcludedGroups="docker"
          ls -la wgc-embedded-server/target
